# Copyright (C) 2017-2022 BinaryMist Limited. All rights reserved.

# Use of this software is governed by the Business Source License
# included in the file /licenses/bsl.md

# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

blank_issues_enabled: false
contact_links:
  - name: BinaryMist
    url: https://binarymist.io/#contact
    about: If you need to contact us directly.
